PUT http://localhost:1234/products/56
content-type: application/json

{
    "updated":"Data",
    "age":56
}

###
POST http://localhost:1234/products
content-type: application/json

{
    "name": "This is POst data",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

####
DELETE http://localhost:1234/products/1

#### Get all
GET http://localhost:1234/products

#### Get One
GET  http://localhost:1234/products/50

