GET http://localhost:1234/

### 
GET http://localhost:1234/hello

### Tesing for Array
GET http://localhost:1234/array

### Testing the Object Route
GET http://localhost:1234/object

### Testing Integration of Arrays and Objects
GET http://localhost:1234/arrAndObj
