GET http://localhost:1234/

### Simplest Routes
GET http://localhost:1234/hello

### Tesing for Array
GET http://localhost:1234/array

### Testing the Object Route
GET http://localhost:1234/object

### Testing Integration of Arrays and Objects
GET http://localhost:1234/arrAndObj


########################################################

### Default Routes Testing Starts here : Q and A
GET http://localhost:1234/qanda
###
GET http://localhost:1234/qanda/55

### Users
GET http://localhost:1234/users
###
GET http://localhost:1234/users/35

### Products
GET http://localhost:1234/products
###
GET http://localhost:1234/products/12

#####################################################
### Request for Array and Object as parent direct

GET http://localhost:1234/arrayParent

###
GET  http://localhost:1234/objectParent

###
GET  http://localhost:1234/char

### Custom array of Objcts
GET  http://localhost:1234/arrayOfObjects
################################################

### Send File over Request
GET  http://localhost:1234/getImg